/**
 * Default shortcut bindings for the browser demo.
 *
 * Mirrors `default_settings()` in apps/src-tauri/src/shortcuts/manager.rs —
 * the demo has no Rust backend, so `getShortcuts` fails and we fall back to
 * this table to keep keyboard shortcuts usable at http://…?demo=1.
 * Keep in sync when the Rust defaults change.
 */
import type { ShortcutBinding } from '@/lib/tauri-api';

export const DEMO_DEFAULT_SHORTCUTS: ShortcutBinding[] = [
  {
    id: 'copy',
    keys: ['ctrl', 'c'],
    action: 'Copy',
    context: 'file-explorer',
    enabled: true,
    profile: 'default',
    description: 'Copy selected items',
    global: false,
    key_combination: 'ctrl+c',
  },
  {
    id: 'cut',
    keys: ['ctrl', 'x'],
    action: 'Cut',
    context: 'file-explorer',
    enabled: true,
    profile: 'default',
    description: 'Cut selected items',
    global: false,
    key_combination: 'ctrl+x',
  },
  {
    id: 'paste',
    keys: ['ctrl', 'v'],
    action: 'Paste',
    context: 'file-explorer',
    enabled: true,
    profile: 'default',
    description: 'Paste items',
    global: false,
    key_combination: 'ctrl+v',
  },
  {
    id: 'delete',
    keys: ['ctrl', 'backspace'],
    action: 'Delete',
    context: 'file-explorer',
    enabled: true,
    profile: 'default',
    description: 'Move to trash',
    global: false,
    key_combination: 'ctrl+backspace',
  },
  {
    id: 'rename',
    keys: ['enter'],
    action: 'Rename',
    context: 'file-explorer',
    enabled: true,
    profile: 'default',
    description: 'Rename selected item',
    global: false,
    key_combination: 'enter',
  },
  {
    id: 'new-folder',
    keys: ['ctrl', 'shift', 'n'],
    action: 'NewFolder',
    context: 'file-explorer',
    enabled: true,
    profile: 'default',
    description: 'Create new folder',
    global: false,
    key_combination: 'ctrl+shift+n',
  },
  {
    id: 'new-file',
    keys: ['ctrl', 'alt', 'n'],
    action: 'NewFile',
    context: 'file-explorer',
    enabled: true,
    profile: 'default',
    description: 'Create new file',
    global: false,
    key_combination: 'ctrl+alt+n',
  },
  {
    id: 'duplicate',
    keys: ['ctrl', 'd'],
    action: 'Duplicate',
    context: 'file-explorer',
    enabled: true,
    profile: 'default',
    description: 'Duplicate selected files',
    global: false,
    key_combination: 'ctrl+d',
  },
  {
    id: 'copy-path',
    keys: ['ctrl', 'alt', 'c'],
    action: 'CopyPath',
    context: 'file-explorer',
    enabled: true,
    profile: 'default',
    description: 'Copy path of selected item',
    global: false,
    key_combination: 'ctrl+alt+c',
  },
  {
    id: 'open-selected',
    keys: ['ctrl', 'o'],
    action: 'Open',
    context: 'file-explorer',
    enabled: true,
    profile: 'default',
    description: 'Open selected item',
    global: false,
    key_combination: 'ctrl+o',
  },
  {
    id: 'open-selected-down',
    keys: ['ctrl', 'down'],
    action: 'Open',
    context: 'file-explorer',
    enabled: true,
    profile: 'default',
    description: 'Open selected item',
    global: false,
    key_combination: 'ctrl+down',
  },
  {
    id: 'properties',
    keys: ['ctrl', 'i'],
    action: 'Properties',
    context: 'file-explorer',
    enabled: true,
    profile: 'default',
    description: 'Show properties of selected item',
    global: false,
    key_combination: 'ctrl+i',
  },
  {
    id: 'navigate-back',
    keys: ['ctrl', '['],
    action: 'NavigateBack',
    context: 'file-explorer',
    enabled: true,
    profile: 'default',
    description: 'Go back',
    global: false,
    key_combination: 'ctrl+[',
  },
  {
    id: 'navigate-forward',
    keys: ['ctrl', ']'],
    action: 'NavigateForward',
    context: 'file-explorer',
    enabled: true,
    profile: 'default',
    description: 'Go forward',
    global: false,
    key_combination: 'ctrl+]',
  },
  {
    id: 'navigate-up',
    keys: ['ctrl', 'up'],
    action: 'NavigateUp',
    context: 'file-explorer',
    enabled: true,
    profile: 'default',
    description: 'Go to parent directory',
    global: false,
    key_combination: 'ctrl+up',
  },
  {
    id: 'go-home',
    keys: ['ctrl', 'shift', 'h'],
    action: 'GoHome',
    context: 'file-explorer',
    enabled: true,
    profile: 'default',
    description: 'Go to home directory',
    global: false,
    key_combination: 'ctrl+shift+h',
  },
  {
    id: 'go-to-path',
    keys: ['ctrl', 'shift', 'g'],
    action: 'GoToPath',
    context: 'file-explorer',
    enabled: true,
    profile: 'default',
    description: 'Focus address bar',
    global: false,
    key_combination: 'ctrl+shift+g',
  },
  {
    id: 'select-all',
    keys: ['ctrl', 'a'],
    action: 'SelectAll',
    context: 'file-explorer',
    enabled: true,
    profile: 'default',
    description: 'Select all files',
    global: false,
    key_combination: 'ctrl+a',
  },
  {
    id: 'invert-selection',
    keys: ['ctrl', 'shift', 'i'],
    action: 'InvertSelection',
    context: 'file-explorer',
    enabled: true,
    profile: 'default',
    description: 'Invert selection',
    global: false,
    key_combination: 'ctrl+shift+i',
  },
  {
    id: 'clear-selection',
    keys: ['esc'],
    action: 'ClearSelection',
    context: 'file-explorer',
    enabled: true,
    profile: 'default',
    description: 'Clear selection',
    global: false,
    key_combination: 'esc',
  },
  {
    id: 'search',
    keys: ['ctrl', 'f'],
    action: 'Search',
    context: 'file-explorer',
    enabled: true,
    profile: 'default',
    description: 'Open search',
    global: false,
    key_combination: 'ctrl+f',
  },
  {
    id: 'quick-search',
    keys: ['ctrl', 'p'],
    action: 'QuickSearch',
    context: 'file-explorer',
    enabled: true,
    profile: 'default',
    description: 'Quick search',
    global: false,
    key_combination: 'ctrl+p',
  },
  {
    id: 'natural-language-search',
    keys: ['ctrl', 'shift', 'f'],
    action: 'NaturalLanguageSearch',
    context: 'file-explorer',
    enabled: true,
    profile: 'default',
    description: 'AI-powered search',
    global: false,
    key_combination: 'ctrl+shift+f',
  },
  {
    id: 'filter-files',
    keys: ['ctrl', 'alt', 'p'],
    action: 'FilterFiles',
    context: 'file-explorer',
    enabled: true,
    profile: 'default',
    description: 'Filter files',
    global: false,
    key_combination: 'ctrl+alt+p',
  },
  {
    id: 'toggle-left-sidebar',
    keys: ['ctrl', 'alt', 's'],
    action: 'ToggleLeftSidebar',
    context: 'file-explorer',
    enabled: true,
    profile: 'default',
    description: 'Toggle left sidebar',
    global: false,
    key_combination: 'ctrl+alt+s',
  },
  {
    id: 'toggle-right-sidebar',
    keys: ['ctrl', 'shift', 'b'],
    action: 'ToggleRightSidebar',
    context: 'file-explorer',
    enabled: true,
    profile: 'default',
    description: 'Toggle right sidebar',
    global: false,
    key_combination: 'ctrl+shift+b',
  },
  {
    id: 'toggle-bottom-panel',
    keys: ['ctrl', 'j'],
    action: 'ToggleBottomPanel',
    context: 'file-explorer',
    enabled: true,
    profile: 'default',
    description: 'Toggle bottom panel',
    global: false,
    key_combination: 'ctrl+j',
  },
  {
    id: 'toggle-preview',
    keys: ['ctrl', 'shift', 'p'],
    action: 'TogglePreview',
    context: 'file-explorer',
    enabled: true,
    profile: 'default',
    description: 'Toggle preview panel',
    global: false,
    key_combination: 'ctrl+shift+p',
  },
  {
    id: 'switch-view-mode',
    keys: ['ctrl', 'shift', 'l'],
    action: 'SwitchViewMode',
    context: 'file-explorer',
    enabled: true,
    profile: 'default',
    description: 'Cycle view mode',
    global: false,
    key_combination: 'ctrl+shift+l',
  },
  {
    id: 'refresh',
    keys: ['f5'],
    action: 'Refresh',
    context: 'file-explorer',
    enabled: true,
    profile: 'default',
    description: 'Refresh directory',
    global: false,
    key_combination: 'f5',
  },
  {
    id: 'toggle-hidden',
    keys: ['ctrl', 'shift', '.'],
    action: 'ToggleHiddenFiles',
    context: 'file-explorer',
    enabled: true,
    profile: 'default',
    description: 'Toggle hidden files',
    global: false,
    key_combination: 'ctrl+shift+.',
  },
  {
    id: 'zoom-in',
    keys: ['ctrl', '='],
    action: 'ZoomIn',
    context: 'file-explorer',
    enabled: true,
    profile: 'default',
    description: 'Zoom in',
    global: false,
    key_combination: 'ctrl+=',
  },
  {
    id: 'zoom-out',
    keys: ['ctrl', '-'],
    action: 'ZoomOut',
    context: 'file-explorer',
    enabled: true,
    profile: 'default',
    description: 'Zoom out',
    global: false,
    key_combination: 'ctrl+-',
  },
  {
    id: 'open-settings',
    keys: ['ctrl', '', ''],
    action: 'OpenSettings',
    context: 'file-explorer',
    enabled: true,
    profile: 'default',
    description: 'Open settings',
    global: false,
    key_combination: 'ctrl+,',
  },
  {
    id: 'close-tab',
    keys: ['ctrl', 'w'],
    action: 'CloseTab',
    context: 'file-explorer',
    enabled: true,
    profile: 'default',
    description: 'Close current tab',
    global: false,
    key_combination: 'ctrl+w',
  },
  {
    id: 'next-tab',
    keys: ['ctrl', 'tab'],
    action: 'NextTab',
    context: 'file-explorer',
    enabled: true,
    profile: 'default',
    description: 'Switch to next tab',
    global: false,
    key_combination: 'ctrl+tab',
  },
  {
    id: 'prev-tab',
    keys: ['ctrl', 'shift', 'tab'],
    action: 'PreviousTab',
    context: 'file-explorer',
    enabled: true,
    profile: 'default',
    description: 'Switch to previous tab',
    global: false,
    key_combination: 'ctrl+shift+tab',
  },
  {
    id: 'toggle-fullscreen',
    keys: ['f11'],
    action: 'ToggleFullscreen',
    context: 'file-explorer',
    enabled: true,
    profile: 'default',
    description: 'Toggle fullscreen',
    global: false,
    key_combination: 'f11',
  },
  {
    id: 'new-window',
    keys: ['ctrl', 'n'],
    action: 'NewWindow',
    context: 'file-explorer',
    enabled: true,
    profile: 'default',
    description: 'Open new window',
    global: false,
    key_combination: 'ctrl+n',
  },
  {
    id: 'quit',
    keys: ['ctrl', 'q'],
    action: 'Quit',
    context: 'file-explorer',
    enabled: true,
    profile: 'default',
    description: 'Quit application',
    global: false,
    key_combination: 'ctrl+q',
  },
  {
    id: 'open-terminal',
    keys: ['ctrl', '`'],
    action: 'OpenTerminal',
    context: 'file-explorer',
    enabled: true,
    profile: 'default',
    description: 'Open terminal',
    global: false,
    key_combination: 'ctrl+`',
  },
];
